server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  client:
    registerWithEureka: false # 表示是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    fetchRegistry: false  # 表示是否从eureka服务器获取注册信息，因为当前这个应用就是eureka服务器，没必要获取自身，所以这里是false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
