server:
  port: 9000
spring:
  application:
    name: springcloudserve
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/,http://eureka8003.com:8003/eureka/    #连接集群环境