server:
  port: 8003
spring:
  application:
    name: springcloud-eureka8003
eureka:
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
  instance:
    hostname: eureka8003.com #eureka\u670D\u52A1\u7AEF\u7684\u5B9E\u4F8B\u540D\u79F0
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #\u5355\u673A defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #\u8BBE\u7F6E\u4E0EEureka Server\u4EA4\u4E92\u7684\u5730\u5740\u67E5\u8BE2\u670D\u52A1\u548C\u6CE8\u518C\u670D\u52A1\u90FD\u9700\u8981\u4F9D\u8D56\u8FD9\u4E2A\u5730\u5740\uFF08\u5355\u673A\uFF09\u3002
      defaultZone: http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/ # \u5C06 8001 \u548C 8002 \u548C 8003 \u914D\u7F6E\u6210\u96C6\u7FA4\u73AF\u5883
